Update Jenkins

diff --git a/Jenkins b/Jenkins
--- a/Jenkins
+++ b/Jenkins
@@ -433,7 +433,102 @@ SETTING UP AGENT:
     Manage Jenkins
     Nodes
 
+TOMCAT DEPLOYMENT IN ec2-user
 
+SETUP:
+1. wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80.tar.gz
+2. tar -zxvf apache-tomcat-9.0.80.tar.gz && cd apache-tomcat-9.0.80
+3. vim webapps/manager/META-INF/context.xml  (delete line 21 and 22)
+4. vim conf/tomcat-users.xml (copy paste those lines in last)
+
+
+  <role rolename="manager-gui"/>
+  <role rolename="manager-script"/>
+  <user username="tomcat" password="raham123" roles="manager-gui, manager-script"/>
+
+5. ./bin/startup.sh
+6. login: public-ip:8080 -- > manager app -- > username: tomcat passowrd:tomcat123 -- > enter
+
+TOMCAT DEPLOYMENT IN BY UING PIPLEINE
+
+pipeline {
+    agent any
+
+    environment {
+        TOMCAT_VERSION = "9.0.80"
+        TOMCAT_HOME = "${WORKSPACE}/apache-tomcat-${TOMCAT_VERSION}"
+        TOMCAT_USER = "tomcat"
+        TOMCAT_PASS = "raham123"
+        TOMCAT_ROLES = "manager-gui,manager-script"
+        TOMCAT_URL = "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80.tar.gz"
+    }
+
+    stages {
+        stage('Download Tomcat') {
+            steps {
+                echo "Downloading Apache Tomcat ${TOMCAT_VERSION}..."
+                sh """
+                    wget -O apache-tomcat-${TOMCAT_VERSION}.tar.gz ${TOMCAT_URL} || { echo 'Download failed'; exit 1; }
+                """
+            }
+        }
+
+        stage('Extract Tomcat') {
+            steps {
+                echo "Extracting Tomcat..."
+                sh """
+                    tar -zxvf apache-tomcat-${TOMCAT_VERSION}.tar.gz
+                """
+            }
+        }
+
+        stage('Configure Manager App') {
+            steps {
+                echo "Updating context.xml..."
+                sh """
+                    if [ -f ${TOMCAT_HOME}/webapps/manager/META-INF/context.xml ]; then
+                        sed -i '21,22d' ${TOMCAT_HOME}/webapps/manager/META-INF/context.xml
+                    else
+                        echo "context.xml not found!"
+                        exit 1
+                    fi
+                """
+            }
+        }
+
+        stage('Configure Users') {
+            steps {
+                echo "Adding manager user..."
+                sh """
+                    cat <<EOL >> ${TOMCAT_HOME}/conf/tomcat-users.xml
+<role rolename="manager-gui"/>
+<role rolename="manager-script"/>
+<user username="${TOMCAT_USER}" password="${TOMCAT_PASS}" roles="${TOMCAT_ROLES}"/>
+EOL
+                """
+            }
+        }
+
+        stage('Start Tomcat') {
+            steps {
+                echo "Starting Tomcat..."
+                sh """
+                    chmod +x ${TOMCAT_HOME}/bin/*.sh
+                    ${TOMCAT_HOME}/bin/startup.sh
+                """
+            }
+        }
+    }
+
+    post {
+        success {
+            echo "Tomcat setup complete! Access manager app at http://<public-ip>:8080/manager"
+        }
+        failure {
+            echo "Tomcat setup failed. Check the logs."
+        }
+    }
+}
 
 
 
